CREATE TABLE IF NOT EXISTS RAW_ORDERS (
    ORDER_ID            INTEGER PRIMARY KEY,
    CREATED_AT          TIMESTAMP_NTZ NOT NULL,
    WEBSITE_SESSION_ID  INTEGER,
    USER_ID             INTEGER,
    PRIMARY_PRODUCT_ID  INTEGER,
    ITEMS_PURCHASED     SMALLINT NOT NULL,
    PRICE_USD           DECIMAL(6,2) NOT NULL,
    COGS_USD            DECIMAL(6,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW_ORDER_ITEMS (
    ORDER_ITEM_ID   INTEGER PRIMARY KEY,
    CREATED_AT      TIMESTAMP_NTZ NOT NULL,
    ORDER_ID        INTEGER,
    PRODUCT_ID      INTEGER,
    IS_PRIMARY_ITEM SMALLINT NOT NULL,
    PRICE_USD       DECIMAL(6,2) NOT NULL,
    COGS_USD        DECIMAL(6,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW_PRODUCTS (
    PRODUCT_ID   INTEGER PRIMARY KEY,
    CREATED_AT   TIMESTAMP_NTZ NOT NULL,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    DESCRIPTION  TEXT
);

CREATE TABLE IF NOT EXISTS RAW_ORDER_ITEM_REFUNDS (
    ORDER_ITEM_REFUND_ID INTEGER PRIMARY KEY,
    CREATED_AT           TIMESTAMP_NTZ NOT NULL,
    ORDER_ITEM_ID        INTEGER,
    REFUND_AMOUNT_USD    DECIMAL(6,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW_USERS (
    USER_ID                 INTEGER PRIMARY KEY,
    FIRST_NAME              TEXT,
    LAST_NAME               TEXT,
    EMAIL                   TEXT,
    PASSWORD_SALT           TEXT,
    PASSWORD_HASH           TEXT,
    BILLING_STREET_ADDRESS  TEXT,
    BILLING_CITY            TEXT,
    BILLING_STATE           TEXT,
    BILLING_POSTAL_CODE     TEXT,
    BILLING_COUNTRY         TEXT,
    SHIPPING_STREET_DDRESS  TEXT,
    SHIPPING_CITY           TEXT,
    SHIPPING_STATE          TEXT,
    SHIPPING_POSTAL_CODE    TEXT,
    SHIPPING_COUNTRY        TEXT,
    CREATED_AT              TIMESTAMP_NTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS RAW_EMPLOYEES (
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    FIRST_NAME  VARCHAR(50),
    LAST_NAME   VARCHAR(50),
    DEPARTMENT  VARCHAR(50),
    SALARY      DECIMAL(10,2),
    EMAIL       VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS RAW_WEBSITE_SESSIONS (
    WEBSITE_SESSION_ID INTEGER PRIMARY KEY,
    CREATED_AT         TIMESTAMP_NTZ NOT NULL,
    USER_ID            INTEGER,
    IS_REPEAT_SESSION  SMALLINT NOT NULL,
    UTM_SOURCE         VARCHAR(12),
    UTM_CAMPAIGN       VARCHAR(20),
    UTM_CONTENT        VARCHAR(15),
    DEVICE_TYPE        VARCHAR(15),
    HTTP_REFERER       VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS RAW_WEBSITE_PAGEVIEWS (
    WEBSITE_PAGEVIEW_ID INTEGER PRIMARY KEY,
    CREATED_AT          TIMESTAMP_NTZ NOT NULL,
    WEBSITE_SESSION_ID  INTEGER,
    PAGEVIEW_URL        VARCHAR(50) NOT NULL
);
